name: waves
channels:
  - conda-forge
dependencies:
  - scipy
  - h5py
  - numpy
  - pip
  - python
  - jupyterlab
  - matplotlib
  - jupytext
  - pandas
  - pip:
      - ngsolve==6.2.2606
      - git+https://github.com/NGSolve/ngs-special-functions.git
      - webgui_jupyter_widgets
